USE testdb;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION
SELECT * FROM Table1
WAITFOR DELAY '00:00:05'
SELECT * FROM Table1
COMMIT TRANSACTION

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

--BEGIN TRANSACTION
--SELECT * FROM Table1
--WAITFOR DELAY '00:00:05'
--SELECT * FROM Table1
--COMMIT TRANSACTION