USE testdb
GO

ALTER DATABASE testdb 
SET ALLOW_SNAPSHOT_ISOLATION ON;

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;

--ALTER DATABASE testdb 
--SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT

BEGIN TRAN
SELECT someint FROM Table2 WHERE id = 1

WAITFOR DELAY '00:00:10';

UPDATE Table2 SET someint = someint + 5 WHERE id = 1